# Run with: container-structure-test test --driver tar --image livingatlases/cas:latest --config container-test.yaml
schemaVersion: 2.0.0
fileExistenceTests:
- name: 'data'
  path: '/data/cas/'
  shouldExist: true
  permissions: 'drwxr-xr-x'
# Does not work:
#  uid: 1000
#  gid: 1000
  isExecutableBy: 'any'
- name: 'logs'
  path: '/var/log/atlas/cas'
  shouldExist: true
  permissions: 'drwxr-xr-x'
#  uid: 1000
#  gid: 1000
  isExecutableBy: 'any'
- name: 'war exits'
  path: '/opt/app.war'
  shouldExist: true
  permissions: '-rw-------'
